version: '3.8'

services:
  api:
    build: .
    
    container_name: blockchain_api_container
    
    ports:
      - "8000:8000"
      
    env_file:
      - .env
      
    volumes:
      - ./src:/app/src

